
[[items]]
type="choice"
title="経験した疾患"
id="diseases"
multiple=true # This item is multiple choice. This is optional. It is false by default.
choices=[
{value="JlvnlXM", title="鉄欠乏性貧血"},
{value="JlvnlYM", title="ビタミンB12欠乏性貧血"},
{value="JlvnlZE", title="播種性血管内凝固<DIC>"},
{value="JlvnlcA", title="脳出血"},
{value="JlvnlcE", title="くも膜下出血"},
{value="JlvnlcQ", title="脳梗塞"},
{value="JlvnlcY", title="一過性脳虚血発作"},
{value="Jlvnlcw", title="脳炎・髄膜炎"},
{value="JlvnldE", title="多発性硬化症"},
{value="JlvnldM", title="Alzheimer型認知症"},
{value="Jlvnldc", title="Parkinson病"},
{value="JlvnleU", title="重症筋無力症"},
{value="Jlvnleo", title="全般てんかん"},
{value="Jlvnles", title="局在関連てんかん"},
{value="Jlvnle0", title="片頭痛"},
{value="Jlvnle8", title="緊張型頭痛"},
{value="JlvnlfU", title="急性硬膜外血腫"},
{value="JlvnlfY", title="硬膜下血腫（急性・慢性）"},
{value="JlvnlgE", title="湿疹反応（湿疹三角）"},
{value="JlvnlgM", title="接触皮膚炎"},
{value="JlvnlgQ", title="アトピー性皮膚炎"},
{value="Jlvnlg4", title="蕁麻疹"},
{value="Jlvnlh8", title="Stevens-Johnson症候群"},
{value="Jlvnljk", title="蜂窩織炎"},
{value="Jlvnlj8", title="疥癬"},
{value="Jlvnlk8", title="後天性免疫不全症候群<AIDS>に伴う皮膚症状（梅毒・難治性ヘルペス・伝染性軟属腫・Kaposi肉腫等）"},
{value="JlvnlkE", title="単純ヘルペス"},
{value="JlvnlkM", title="帯状疱疹"},
{value="Jlvnlkc", title="麻疹"},
{value="Jlvnlkk", title="風疹"},
{value="Jlvnlko", title="水痘"},
{value="JlvnlmI", title="褥瘡"},
{value="Jlvnlpc", title="脊髄損傷"},
{value="Jlvnlnk", title="骨折"},
{value="Jlvnlnw", title="骨粗鬆症"},
{value="Jlvnlpg", title="脊椎椎間板ヘルニア"},
{value="Jlvnlpo", title="脊柱管狭窄症"},
{value="Jlvnloc", title="変形性関節症"},
{value="Jlvnlr8", title="労作性狭心症"},
{value="JlvnlsE", title="冠攣縮性狭心症"},
{value="JlvnlsI", title="不安定狭心症"},
{value="JlvnlsQ", title="急性心筋梗塞"},
{value="Jlvnlsc", title="房室ブロック"},
{value="Jlvnlsg", title="心房細動"},
{value="Jlvnlso", title="心房粗動"},
{value="Jlvnlsw", title="発作性上室頻拍症"},
{value="Jlvnls0", title="心室頻拍"},
{value="JlvnltA", title="心室細動"},
{value="JlvnltI", title="期外収縮(上室性・心室性)"},
{value="Jlvnltg", title="僧帽弁疾患(狭窄・閉鎖不全)"},
{value="Jlvnlts", title="大動脈弁疾患（狭窄・閉鎖不全）"},
{value="JlvnluA", title="特発性心筋症（肥大型・拡張型・拘束型）"},
{value="JlvnluY", title="急性心筋炎"},
{value="Jlvnlug", title="感染性心内膜炎"},
{value="JlvnlvY", title="急性大動脈解離"},
{value="Jlvnlvc", title="大動脈瘤（胸部・腹部）"},
{value="Jlvnlvk", title="閉塞性動脈硬化症"},
{value="Jlvnlv0", title="深部静脈血栓症"},
{value="JlvnlwI", title="下肢静脈瘤"},
{value="Jlvnlwo", title="起立性低血圧"},
{value="JlvnlxA", title="急性上気道感染症（かぜ症候群）"},
{value="JlvnlxI", title="扁桃炎"},
{value="J-RA37E", title="気管支炎"},
{value="Jlvnlxc", title="肺炎（定型・非定型）"},
{value="Jlvnlxg", title="肺結核症"},
{value="JlvnlyE", title="慢性閉塞性肺疾患（COPD）"},
{value="JlvnlyQ", title="気管支喘息（咳喘息を含む）"},
{value="JlvnlzI", title="肺血栓塞栓症"},
{value="Jlvnl0I", title="睡眠時無呼吸症候群"},
{value="J-RA9r4", title="急性呼吸促(窮)迫症候群<ARDS>"},
{value="Jlvnl1A", title="気胸（自然・緊張性・外傷性）"},
{value="Jlvnl2E", title="食道・胃静脈瘤"},
{value="Jlvnl2M", title="胃食道逆流症<GERD>"},
{value="Jlvnl2k", title="消化性潰瘍（胃潰瘍・十二指腸潰瘍)"},
{value="Jlvnl3Q", title="機能性消化管障害（機能性ディスペプシア）"},
{value="Jlvnl3k", title="急性虫垂炎"},
{value="Jlvnl3o", title="腸閉塞"},
{value="Jlvnl30", title="痔核・痔瘻"},
{value="Jlvnl4o", title="便秘症"},
{value="Jlvnl34", title="機能性消化管障害（過敏性腸症候群）"},
{value="Jlvnl3s", title="潰瘍性大腸炎"},
{value="Jlvnl3w", title="Crohn病"},
{value="Jlvnl28", title="急性胃腸炎"},
{value="Jlvnl50", title="A型肝炎"},
{value="Jlvnl54", title="B型肝炎"},
{value="Jlvnl6A", title="C型肝炎"},
{value="Jlvnl6Q", title="急性肝炎"},
{value="Jlvnl6Y", title="慢性肝炎"},
{value="Jlvnl6g", title="急性肝不全"},
{value="Jlvnl7c", title="脂肪肝"},
{value="Jlvnl64", title="アルコール性肝障害"},
{value="Jlvnl6k", title="門脈圧亢進症"},
{value="Jlvnl6s", title="肝性脳症"},
{value="Jlvnl6w", title="肝癌"},
{value="Jlvnl5M", title="胆石症"},
{value="Jlvnl5U", title="胆嚢炎"},
{value="Jlvnl5Y", title="胆管炎"},
{value="Jlvnl7k", title="急性膵炎（アルコール性・胆石性・特発性）"},
{value="Jlvnl7o", title="慢性膵炎（アルコール性・特発性）"},
{value="Jlvnl70", title="腹膜炎"},
{value="Jlvnl8E", title="鼠径部ヘルニア"},
{value="Jlvnl8Q", title="急性腎障害<AKI>"},
{value="Jlvnl8U", title="慢性腎臓病<CKD>"},
{value="Jlvnl8g", title="高・低ナトリウム血症"},
{value="Jlvnl8o", title="高・低カリウム血症"},
{value="Jlvnl8s", title="高・低カルシウム血症"},
{value="Jlvnl9M", title="急性糸球体腎炎"},
{value="Jlvnl9U", title="IgA腎症"},
{value="Jlvnl9Y", title="膜性腎症"},
{value="Jlvnl9k", title="微小変化群"},
{value="Jlvnl-M", title="急性腎盂腎炎"},
{value="Jlvnl-Q", title="糖尿病腎障害"},
{value="Jlvnl_I", title="尿路結石"},
{value="Jlvnl_Q", title="膀胱炎"},
{value="Jlvnl_U", title="前立腺炎"},
{value="Jlvnl_c", title="尿道炎"},
{value="Jlvnl_0", title="前立腺肥大症"},
{value="JlvnmAo", title="機能性月経困難症"},
{value="JlvnmA0", title="更年期障害"},
{value="JlvnmBA", title="子宮筋腫・子宮腺筋症"},
{value="JlvnmBE", title="子宮内膜症"},
{value="JlvnmBk", title="異所性妊娠"},
{value="JlvnmBs", title="流産・切迫流産"},
{value="JlvnmB4", title="妊娠高血圧症候群"},
{value="JlvnmCM", title="切迫早産"},
{value="JlvnmCY", title="早産"},
{value="JlvnmEs", title="急性白血病"},
{value="JlvnmE4", title="熱性けいれん"},
{value="JlvnmFA", title="脳性麻痺"},
{value="JlvnmGY", title="細気管支炎"},
{value="JlvnmGw", title="腸重積症"},
{value="JlvnmG8", title="乳児下痢症"},
{value="JlvnmHI", title="鼠径ヘルニア"},
{value="JlvnmHU", title="ネフローゼ症候群"},
{value="JlvnmK8", title="甲状腺機能亢進症"},
{value="JlvnmLA", title="甲状腺機能低下症"},
{value="JlvnmL0", title="1型糖尿病"},
{value="JlvnmL8", title="2型糖尿病"},
{value="JlvnmMA", title="糖尿病ケトアシドーシス"},
{value="JlvnmMI", title="高血糖高浸透圧症候群"},
{value="JlvnmMU", title="糖尿病性網膜症"},
{value="JlvnmMY", title="糖尿病性腎症"},
{value="JlvnmMg", title="糖尿病性神経障害"},
{value="JlvnmMk", title="足病変"},
{value="JlvnmMw", title="脂質異常症"},
{value="JlvnmNE", title="高尿酸血症・痛風"},
{value="JlvnmNs", title="結膜炎・角膜炎"},
{value="JlvnmN4", title="白内障"},
{value="JlvnmN8", title="緑内障"},
{value="JlvnmOQ", title="糖尿病・高血圧による眼底変化（糖尿病網膜症など）"},
{value="JlvnmO0", title="中耳炎（急性・慢性・滲出性・真珠腫性）"},
{value="JlvnmPg", title="良性発作性頭位めまい症"},
{value="JlvnmPo", title="Ménière病"},
{value="JlvnmP0", title="鼻出血"},
{value="JlvnmP4", title="副鼻腔炎（急性・慢性）"},
{value="JlvnmQA", title="アレルギー性鼻炎"},
{value="JlvnmQU", title="咽頭炎"},
{value="JlvnmTI", title="頸部リンパ節転移等"},
{value="JlvnmT0", title="うつ病"},
{value="JlvnmT4", title="双極性障害（躁うつ病）"},
{value="JlvnmUA", title="統合失調症"},
{value="JlvnmUY", title="身体症状症（身体化障害・疼痛性障害・心気症）"},
{value="JlvnmTU", title="認知症"},
{value="JmxLo0Y", title="関節リウマチ"},
{value="JmxLo0g", title="全身性エリテマトーデス（SLE）及び合併症（中枢神経ループス、ループス腎炎、抗リン脂質抗体症候群）"},
{value="JlvnmWs", title="IgA血管炎"},
{value="JlvnmW0", title="川崎病"},
{value="JmxLo1A", title="後天性免疫不全症（AIDS）"},
{value="JlvnmXE", title="髄膜脳炎"},
{value="JlvnmXY", title="血流感染・感染性心内膜炎"},
{value="JlvnmXo", title="膀胱炎・腎盂腎炎"},
{value="JlvnmX4", title="血管内留置カテーテル関連感染"},
{value="JlvnmX8", title="尿路カテーテル感染"},
{value="JlvnmYI", title="手術部位感染"},
{value="JlvnmcI", title="肺癌"},
{value="Jlvnmcg", title="食道癌"},
{value="Jlvnmco", title="胃癌"},
{value="Jlvnmc0", title="大腸癌"},
{value="JlvnmdA", title="原発性肝癌"},
{value="JlvnmdQ", title="膵癌"},
{value="JlvnmdY", title="腎癌"},
{value="Jlvnmdg", title="腎盂尿管癌・膀胱癌"},
{value="Jlvnmdk", title="前立腺癌"},
{value="Jlvnmdw", title="子宮頸癌"},
{value="Jlvnmd4", title="子宮体癌（子宮内膜癌）"},
{value="JlvnmeA", title="卵巣腫瘍"},
{value="JlvnmeQ", title="原発性乳癌"},


]